# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [kai9987kai]
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://paypal.me/pools/c/7Z8APS8RbS', 'kai9987kai.pw']
